### ISSUE TITLE
회원가입이 안 됩니다.

### ISSUE THREAD

**Issue by minty99** [swsnu/swpp18-team5#131]
<img width="761" alt="screenshot at dec 12 19-08-43" src="https://user-images.githubusercontent.com/3724119/49862391-71c70d80-fe41-11e8-91a3-7c3f7f0d7aed.png">

회원가입시 이렇게 됩니다.

**Comment by minty99** [comment]
아닌가..? 정상인거 같기도 합니다. 근데 이메일과 패스워드를 입력하고 나서 sign up을 누르면 해당되는 필드들은 자동으로 채워져야 할 것 같습니다.

**Comment by pbzweihander** [comment]
다음부턴 bug reporting template을 따라주세요.

username이 자동으로 채워져야한다는 뜻인가요?

**Comment by minty99** [comment]
앗 죄송합니다.

네, sign up을 하기 전에 아이디 비번을 입력한 경우 자동으로 채워지는 게 직관적이지 않을까요? 하나의 제안입니다.

**Comment by pbzweihander** [comment]
별로 직관적인것 같지는 않고 있으면 편리한 기능인 것 같지만, 현재 우선순위에서 밀리고 딱히 중요하진 않은 것 같네요.
