### ISSUE TITLE
party 수가 너무 늘어나면 화면 스크롤이 되지 않습니다.

### ISSUE THREAD

**Issue by baiksw1997** [swsnu/swpp18-team5#135]
<img width="960" alt="default" src="https://user-images.githubusercontent.com/33816741/49862895-7b9d4080-fe42-11e8-9eac-14a5cb13055f.png">

의도된 건가요?

**Comment by pbzweihander** [comment]
다음부터는 bug reporting template을 따라주세요.

CSS 버그인 것 같습니다. 감사합니다.

**Comment by pbzweihander** [comment]
파티 생성 버튼이 보이지 않는 것은 파티에 참가하고 있어서 그렇습니다. `My`라고 적힌 뱃지가 보이는 걸로 봐서는 이미 파티에 참가중이신거 같네요.

**Comment by kipa00** [comment]
This bug will be resolved on PR #149. Thanks for the bug report!
