### ISSUE TITLE
파티 생성 버튼이 안 보입니다

### ISSUE THREAD

**Issue by hyeminhaleykim** [swsnu/swpp18-team5#136]
**Describe the bug**
lobby 페이지에서 (+) 버튼(파티 생성 버튼)이 보여야할 것 같은데, 보이지 않습니다. 

**To Reproduce**
1. Go to 'lobby page'
2. There is no 'party create button'

**Expected behavior**
파티 생성 버튼이 보여야할 것 같습니다.

**Screenshots**
<img width="1549" alt="2018-12-12 7 23 48" src="https://user-images.githubusercontent.com/29699486/49863365-7b517500-fe43-11e8-9d71-398b90dec555.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] safari
 - Version [e.g. 22] 12.0.2

**Additional context**

**Comment by pbzweihander** [comment]
현재 파티에 참가해있어서 발생하는 문제 아닐까요?

**Comment by hyeminhaleykim** [comment]
크롬으로 접속하니 됩니다. 사파리 css 문제였던 것 같습니다.

**Comment by pbzweihander** [comment]
사파리에서 테스트 후 개선하도록 합시다
