### ISSUE TITLE
SWPP Team1 Code-Review #18

### ISSUE THREAD

**Issue by KyoungWan** [swsnu/swpp18-team5#66]
1. backend/api/view.py 
 - signup, signin 메소드내에서 import구분을 부르시는데, 이 문법이 잘 이해되지 않습니다. 다른 액션들과의 통일성을 해치는 듯해서 수정을 제안드립니다.
2. select-menu.component, line 29
const requestMenu: number = this.menuId === undefined ? undefined : +this.menuId; 가 이해되지 않는데요 뒤에 +this.menuId가 menuId를 양수로 만들기 위함인가요? 그리고 undefined를 === 로 체크하지 않고
const requestMenu:number = this.menuId ? +this.menuId : undefined 처럼 진행해도 괜찮을것 같습니다.

**Comment by pbzweihander** [comment]
Resolved in #85, #86
